ICPSR Weblog Analysis - How are people using the ICPSR web site?
========================================================

Stat Package Format Histograms
--------------------------------------------------------

### All statistical package formats downloaded overall, color-coded by country:

```{r echo=FALSE}
library(DBI)
library(RSQLite)
library(ggplot2)
library(plyr)


# Connect to the database...
driver<-dbDriver("SQLite")
connect<-dbConnect(driver, dbname = "../db/weblogs.db")

# Retrieve all weblog entries for stat package reports and define factors...
log.entries = dbGetQuery(connect, "
select wl.timestamp, u.name as institution, c.name as country, c.abbr as abbr, wl.study, wl.browser_type,
    case
        when wl.format like '%spss%' then 'SPSS'
        when wl.format like '%stata%' then 'STATA'
        when wl.format like '%sas%' then 'SAS'
        when wl.format = 'ascii' or wl.format = 'delimited' or wl.format = 'other' then 'DELIMITED'
        else wl.format
    end as format,
    case
        when (browser_type like 'Mozilla%' or browser_type like 'Opera%' or browser_type like 'Safari%' or browser_type like 'Nokia%' or browser_type like 'BlackBerry%') and
             (browser_type not like '%Yandex%' and browser_type not like '%spider%' and browser_type not like '%Babya Discover%'
              and browser_type not like '%bot%' and browser_type not like '%Daumoa%' and browser_type not like '%crawler%' and browser_type not like '%LinkCheck%'
              and browser_type not like '%WebCorp%' and browser_type not like '%Yahoo! Slurp%' and browser_type not like '%Genieo%') then 'Human'
        when browser_type like '%CopperEgg%' or browser_type like '%InterMapper%' then 'ICPSR-Bot'
        else 'Bot'
    end as accessor
from weblog_downloads wl left outer join country_ips ci on wl.long_ip = ci.long_ip
                         left outer join countries c on ci.country_id = c.id
                         left outer join university_ips ui on (wl.abyte = ui.abyte and wl.bbyte = ui.bbyte and wl.cbyte = ui.cbyte and wl.dbyte >= ui.dbyte1 and wl.dbyte <= ui.dbyte2)
                         left outer join universities u on ui.university_id = u.id
")

log.entries$country <- factor(log.entries$country)
log.entries$abbr <- factor(log.entries$abbr)
log.entries$format <- factor(log.entries$format)
log.entries$accessor <- factor(log.entries$accessor)
log.entries$institution <- factor(log.entries$institution)

# All statistical packages used by humans overall, color-coded by country...
log.entries = subset(log.entries, accessor = 'Human')
ggplot(log.entries, aes(format, colour = abbr, fill = abbr)) +
        geom_histogram() + ylab("Count") + xlab("Format") +
        labs(title = "Overall Downloads by Format") + 
        guides(col=guide_legend(ncol=3, byrow=T))
```

### All statistical package formats downloaded by country with missing country data (NA) removed:

```{r echo=FALSE}
# All statistical packages by country with NA removed...
log.entries.nona = subset(log.entries, !(is.na(abbr)))
ggplot(log.entries.nona, aes(format, colour = abbr, fill = abbr)) +
  geom_histogram() + ylab("Count") + xlab("Format") +
  labs(title = "Download Format by Country") + 
  guides(col=guide_legend(ncol=3, byrow=T))
```

### All statistical package formats downloaded by country with NA and 'US' removed:

```{r echo=FALSE}

# All statistical packages by country with NA and 'US' removed...
log.entries.nous = subset(log.entries.nona, abbr != 'US')
ggplot(log.entries.nous, aes(format, colour = abbr, fill = abbr)) +
  geom_histogram() + ylab("Count") + xlab("Format") +
  labs(title = "Download Format by Country ('US' Excluded)") + 
  guides(col=guide_legend(ncol=3, byrow=T))
```
